---
name: Nix Flake Update

on:
  schedule:
    # Run every Sunday at 1 AM UTC
    - cron: "0 1 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/determinate-nix-action@a18f73c54ca8525de051e73c31512a67f44df919 # v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update Nix flake inputs"
          pr-assignees: Cserny
          pr-reviewers: Cserny
          pr-labels: |
            dependencies
            automated

  lint:
    name: Lint
    uses: ./.github/workflows/_lint.yml
    needs: nix-flake-update

  pytest:
    name: Pytest
    uses: ./.github/workflows/_pytest.yml
    needs: lint

  install:
    name: Install
    uses: ./.github/workflows/_install.yml
    needs: pytest

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [lint, pytest, install]
    if: always()
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check all jobs passed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
